#!/usr/bin/env bash
set -o nounset
set -o errexit

root_dir="$1"
basedir="$1/$2"
targetdir="$1/$3"
logdir="${targetdir}/logs"

start00=$(tsf)
source dirstruct "${basedir}" "${targetdir}"

: '
if [[ ! -d "$logdir" ]]; then
	mkdir -p "${logdir}"
fi

find "${basedir}" -mindepth 0 -type d > "${logdir}/01basedirls"
find "${targetdir}" -mindepth 0 -type d -not -path "${logdir}" > "${logdir}/02targetdirls"

touch "${logdir}/01basefilels"
#touch "${logdir}/02targetfilels"

while IFS= read -r fline; do
	find "$fline" -maxdepth 1 -type f \( -iname \*.flac -o -iname \*.wav -o -iname \*.aif -o -iname \*.aiff \) | sort -n >> "${logdir}/01basefilels"
done < "${logdir}/01basedirls"

while IFS= read -r aline01; do
        mkdir -p "$aline01/logs"
done < "${logdir}/02targetdirls"

flacfn () {
	while IFS= read -r aline; do
		start01=$(tsf)
		
		targetbase="$(printf '%s\n' "$aline" | sed 's/\/[^/]*$//' | sed -r "s#${basedir}#${targetdir}#g")"
		targetformat=".flac"

		filename01_full="$(printf '%s\n' "$aline" | sed 's/^[^:]*[/]//')"
		filename02_base="$(printf '%s\n' "${filename01_full}" | sed 's/\.[^\.]*$//')"
		format01_test=$(printf '%s\n' "${filename01_full}" | awk -F "." '{print NF-1}')
		
		if [[ ${format01_test} -ne 0 ]]; then
			rootformat="$(printf '%s\n' "${filename01_full}" | sed 's/.*\././')"
		fi

		targetfilename02="${filename02_base}""${targetformat}"
		targetfilepath="${targetbase}/${targetfilename02}"
		targetinfofilepath="${targetbase}/logs/${filename02_base}.md"
		targetspecfilepath="${targetbase}/logs/${filename02_base}.png"
		
		startflac=$(tsf)

		if [[ "${rootformat}" == "wav" || "${rootformat}" == "aif" || "${rootformat}" == "aiff" ]]; then
			flac -l 0 --disable-constant-subframes --disable-fixed-subframes --no-preserve-modtime --keep-foreign-metadata -V -o "${targetfilepath}" "$aline"
		else
			flac -l 0 --disable-constant-subframes --disable-fixed-subframes --no-preserve-modtime -V -o "${targetfilepath}" "$aline"
		fi

		endflac=$(tsf)
		
		cd "${targetbase}/"
		
		startffmpeg=$(tsf)
		ffmpeg -nostdin -i "${targetfilename02}" -lavfi showspectrumpic "${targetspecfilepath}"
		endffmpeg=$(tsf)
		
		end01=$(tsf)
		flacproctime=$(source prtime 0 "${startflac}" "${endflac}")
		ffmpegproctime=$(source prtime 0 "${startffmpeg}" "${endffmpeg}")
		totproctime=$(source prtime 0 "${start01}" "${end01}")
		printf 'flac proccesing time: %s seconds\n' "${flacproctime}" > "${targetinfofilepath}"
		printf 'ffmpeg spectrogram proccesing time: %s seconds\n' "${ffmpegproctime}" >> "${targetinfofilepath}"
		printf 'total proccesing time: %s seconds\n\n\n' "${totproctime}" >> "${targetinfofilepath}"
		exiftool -a -G1 -s "${targetfilename02}" >> "${targetinfofilepath}"
	done < "${logdir}/01basefilels"
}

flacfn "${basedir}" "${targetdir}"

end00=$(tsf)
totrunningtime_sec=$(source prtime 0 "${start00}" "${end00}")
totrunningtime_min=$(source prtime 1 "${start00}" "${end00}")
totrunningtime_hr=$(source prtime 2 "${start00}" "${end00}")
printf 'total running time flac_uncompressed: %s seconds\n' "${totrunningtime_sec}" > "${logdir}/timelog"
printf 'total running time flac_uncompressed: %s minutes\n' "${totrunningtime_min}" >> "${logdir}/timelog"
printf 'total running time flac_uncompressed: %s hours\n' "${totrunningtime_hr}" >> "${logdir}/timelog"
'

