CC=gcc

#all: flac_uncmp04

#flac_uncmp04: flac_uncmp04_fix_empty_structure.c
#	$(CC) flac_uncmp04_fix_empty_structure.c -o flac_uncmp04

flac_uncmp04: flac_uncmp04_fix_empty_structure.c
	gcc flac_uncmp04_fix_empty_structure.c -o flac_uncmp04

clean:
	rm flac_uncmp04
