#!/usr/bin/env bash

argsarray=("$@")
rootd="${argsarray[0]}"
based="${argsarray[1]}"
targetd="${argsarray[2]}"

printf '%s\n' "${argsarray[@]}"
printf '%s\n' "${rootd}"
printf '%s\n' "${based}"
printf '%s\n' "${targetd}"

#R --no-save --verbose CMD BATCH --args ${rootd} ${based} ${targetd} /laynestaley88/jdhaltrich/linuxstp/dev/script/flac/v1_2/src/R/v1_2_r2/flac_uncmp2_01_b.R
Rscript --no-save --no-restore --verbose /laynestaley88/jdhaltrich/linuxstp/dev/script/flac/v1_2/src/R/v1_2_r2/flac_uncmp2_01_b.R
